// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package internal

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkUserExists = `-- name: CheckUserExists :one
SELECT EXISTS(
    SELECT 1 FROM "user" WHERE "id" = $1
) as "user_exists"
`

func (q *Queries) CheckUserExists(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserExists, id)
	var user_exists bool
	err := row.Scan(&user_exists)
	return user_exists, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO "user" (
    "first_name",
    "last_name",
    "email",
    "password",
    "phone_number",
    "role"
) VALUES (
             $1, $2, $3, $4, $5, $6
         ) RETURNING id, first_name, last_name, email, password, phone_number, role, created_at, updated_at
`

type CreateUserParams struct {
	FirstName   string
	LastName    string
	Email       string
	Password    []byte
	PhoneNumber pgtype.Text
	Role        UserRole
}

// =============================================================================
// USER TABLE CRUD OPERATIONS
// =============================================================================
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Password,
		arg.PhoneNumber,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.PhoneNumber,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserByEmail = `-- name: DeleteUserByEmail :exec
DELETE FROM "user"
WHERE "email" = $1
`

func (q *Queries) DeleteUserByEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteUserByEmail, email)
	return err
}

const deleteUserByID = `-- name: DeleteUserByID :exec
DELETE FROM "user"
WHERE "id" = $1
`

func (q *Queries) DeleteUserByID(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUserByID, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    "id",
    "first_name",
    "last_name",
    "email",
    "phone_number",
    "role",
    "created_at",
    "updated_at"
FROM "user"
WHERE "email" = $1
`

type GetUserByEmailRow struct {
	ID          int32
	FirstName   string
	LastName    string
	Email       string
	PhoneNumber pgtype.Text
	Role        UserRole
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    "id",
    "first_name",
    "last_name",
    "email",
    "phone_number",
    "role",
    "created_at",
    "updated_at"
FROM "user"
WHERE "id" = $1
`

type GetUserByIDRow struct {
	ID          int32
	FirstName   string
	LastName    string
	Email       string
	PhoneNumber pgtype.Text
	Role        UserRole
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserWithPasswordById = `-- name: GetUserWithPasswordById :one
SELECT
    "id",
    "first_name",
    "last_name",
    "email",
    "password",
    "phone_number",
    "role",
    "created_at",
    "updated_at"
FROM "user"
WHERE "id" = $1
`

func (q *Queries) GetUserWithPasswordById(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserWithPasswordById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.PhoneNumber,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT
    "id",
    "first_name",
    "last_name",
    "email",
    "phone_number",
    "role",
    "created_at",
    "updated_at"
FROM "user"
WHERE
  -- Role filter (optional - pass NULL to ignore)
    ($1::text IS NULL OR $1 = '' OR "role"::text = $1)
  AND
  -- Search filter (optional - pass NULL or empty string to ignore)
    ($2::text IS NULL OR $2 = '' OR
     "first_name" ILIKE '%' || $2 || '%' OR
     "last_name" ILIKE '%' || $2 || '%' OR
     "email" ILIKE '%' || $2 || '%')
ORDER BY
    CASE
        WHEN $2::text IS NOT NULL AND $2 != '' THEN "last_name"
        ELSE NULL
END DESC,
    CASE
        WHEN $2::text IS NOT NULL AND $2 != '' THEN "first_name"
        ELSE NULL
END DESC,
    CASE
        WHEN $2::text IS NULL OR $2 = '' THEN "created_at"
        ELSE NULL
END DESC
LIMIT $3 OFFSET $4
`

type ListUsersParams struct {
	Column1 string
	Column2 string
	Limit   int32
	Offset  int32
}

type ListUsersRow struct {
	ID          int32
	FirstName   string
	LastName    string
	Email       string
	PhoneNumber pgtype.Text
	Role        UserRole
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.PhoneNumber,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPartial = `-- name: UpdateUserPartial :one
UPDATE "user"
SET
    "first_name" = COALESCE($1, "first_name"),
    "last_name" = COALESCE($2, "last_name"),
    "email" = COALESCE($3, "email"),
    "phone_number" = COALESCE($4, "phone_number"),
    "password" = COALESCE($5, password),
    "role" = COALESCE($6, "role"),
    "updated_at" = CURRENT_TIMESTAMP
WHERE "id" = $7
    RETURNING id, first_name, last_name, email, password, phone_number, role, created_at, updated_at
`

type UpdateUserPartialParams struct {
	FirstName   pgtype.Text
	LastName    pgtype.Text
	Email       pgtype.Text
	PhoneNumber pgtype.Text
	Password    []byte
	Role        NullUserRole
	ID          int32
}

func (q *Queries) UpdateUserPartial(ctx context.Context, arg UpdateUserPartialParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPartial,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PhoneNumber,
		arg.Password,
		arg.Role,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.PhoneNumber,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
